name: speed_temp_slider
description: "A beautiful temperature and speed slider plugin for Flutter!"
version: 0.0.1
homepage: https://github.com/algrassi/speed_temp_slider
repository: https://github.com/algrassi/speed_temp_slider
issue_tracker: https://github.com/algrassi/speed_temp_slider/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
